# Generated by Django 4.2.1 on 2023-10-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': [('user_management', 'Can create, change and delete developer')]},
        ),
    ]
