# Generated by Django 4.2.1 on 2023-10-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='user_name',
        ),
    ]
